---
all:
  children:
    distribution_switches:
      hosts:
        DIST-SW-01:
          ansible_host: 192.168.100.2
          ansible_network_os: ios
          ansible_connection: network_cli
          ansible_user: admin
          ansible_password: "{{ vault_ansible_password }}"
          mgmt_ip: 192.168.100.2
          location: "Main Data Center - Row B"
          role: distribution_switch
          model: Catalyst-9300
          os_version: "17.3.3"
          verify_variables:
            - name: verify_vlan
              vlans:
                - 10  # USER-VLAN-10
                - 20  # USER-VLAN-20
                - 30  # VOICE-VLAN
                - 100 # MGMT-VLAN
            - name: verify_ip
              interfaces:
                - GigabitEthernet1/0/1
                - Vlan100
          uplinks:
            - device: ASR-CORE-01
              interface: GigabitEthernet1/0/1
              remote_interface: GigabitEthernet0/0/0
          downlinks:
            - device: ACCESS-SW-01
              interface: GigabitEthernet1/0/2
              remote_interface: GigabitEthernet1/0/1
            - device: ACCESS-SW-02
              interface: GigabitEthernet1/0/3
              remote_interface: GigabitEthernet1/0/1 