---
all:
  children:
    core_routers:
      hosts:
        ASR-CORE-01:
          ansible_host: 192.168.1.1
          ansible_network_os: ios
          ansible_connection: network_cli
          ansible_user: admin
          ansible_password: "{{ vault_ansible_password }}"
          mgmt_ip: 192.168.1.1
          location: "Main Data Center"
          role: core_router
          model: ASR-1000
          os_version: "17.3.3"
          verify_variables:
            - name: verify_ip
              interfaces:
                - GigabitEthernet0/0/0
                - GigabitEthernet0/0/1
                - GigabitEthernet0/0/2 